## Unir las bases de datos

Limpiar la base de datos de las elecciones y luego limpiar las bases de datos de CASEN para saber bien que variables vamos a usar.

# Insertar librerías que vamos a usar

```{r}
library(tidyverse)
library(readxl)
library(janitor)
```

# Código para limpiar base 1: Elecciones

```{r}
# Subir bases de datos
pleb_2022 <- read_excel("input/Resultados-Plebiscito-Constitucional-2022.xlsx")
pleb_2023 <- read_excel("input/2023_PlebiscitoConstitucional_DatosPlebiscito.xlsx")

# Limpiar las bases partiendo por la del plebiscito del 2022
pleb_2022 <- clean_names(pleb_2022) |> 
  select(comuna, opcion, votos_tricel) 

pleb_2022 <- pleb_2022 |> 
  group_by(comuna, opcion) |>
  summarise(total_votos = sum(votos_tricel, na.rm = TRUE)) |>
  ungroup()

pleb_2022 <- pleb_2022 |>
  pivot_wider(
    names_from = opcion,
    values_from = total_votos,
    values_fill = 0
  )

pleb_2022 <- clean_names(pleb_2022) |> 
  select(comuna, apruebo, rechazo, votos_en_blanco, votos_nulos)

pleb_2022 <- pleb_2022 |> 
  mutate(
    comuna = str_replace_all(comuna, "LLAILLAY", "LLAY-LLAY"),
    comuna = str_replace_all(comuna, "PAIGUANO", "PAIHUANO")
  )

# Limpiar la base del plebiscito del 2023

pleb_2023 <- clean_names(pleb_2023) |> 
  select(comuna, opciones, votos)

pleb_2023 <- pleb_2023 |>
  group_by(comuna, opciones) |>
  summarise(total_votos = sum(votos, na.rm = TRUE)) |>
  ungroup()

pleb_2023 <- pleb_2023 |>
  pivot_wider(
    names_from = opciones,
    values_from = total_votos,
    values_fill = 0
  )

pleb_2023 <- clean_names(pleb_2023)

pleb_2023 <- pleb_2023 |> 
  mutate(
    comuna = str_replace_all(comuna, "LLAILLAY", "LLAY-LLAY"),
    comuna = str_replace_all(comuna, "PAIGUANO", "PAIHUANO")
  )

# Unir las bases

plebs_final <- full_join(
  pleb_2022,
  pleb_2023,
  by = "comuna",
  suffix = c("_2022", "_2023")
)

# Guardar la base final limpia de los plebiscitos

write_csv(plebs_final, "data/plebiscitos_limpio.csv")
```

# Código para limpiar base 2

```{r}
#Se ocupan las mismas librerías

#Subir bases de datos: 

Nivel_educación <- read_xlsx("C:/Users/USER/OneDrive - Universidad Católica de Chile/Documentos/Proyecto_Medicion/P7_Educacion_2.xlsx") 

Sexo_educación <- read_xlsx("C:/Users/USER/OneDrive - Universidad Católica de Chile/Documentos/Proyecto_Medicion/P7_Educacion_4.xlsx")

#Limpiamos las bases, comenzamos con Nivel_educación

Nivel_educación <- clean_names(Nivel_educación) |> 
  select(codigo_comuna, comuna, poblacion_censada, nunca_asistio, diferencial, parvularia, basica, media, superior, nivel_educativo_no_declarado) |>
  filter(!is.na(comuna))
 
#Limpiamos base de datos Sexo_educación

Sexo_educación <- clean_names(Sexo_educación) |> 
  select(codigo_comuna, comuna, sexo, 
         anos_de_escolaridad_promedio_para_la_poblacion_de_18_anos_o_mas) |>
  filter(!grepl("Total", sexo, ignore.case = TRUE) & !is.na(comuna))
  
#Ahora ocuparemos edad y genero en una nueva base de datos

edad_comuna <- read_xlsx("C:/Users/USER/OneDrive - Universidad Católica de Chile/Documentos/Proyecto_Medicion/input/D1_Poblacion-censada-por-sexo-y-edad-en-grupos-quinquenales.xlsx", sheet = "4", skip = 3)

#Limpiamos base edad_comuna

edad_comuna <- clean_names(edad_comuna) |> 
  select(codigo_comuna, comuna, grupos_de_edad, poblacion_censada, hombres, mujeres, razon_hombre_mujer) |>
  filter(!grepl("País", comuna, ignore.case = TRUE) & !is.na(comuna)) |> 
  filter(!grupos_de_edad %in% c("0 a 4", "5 a 9", "10 a 14", "15 a 19"))

edad_comuna |> 
  count(grupos_de_edad)

#Falta agregar porcentaje y unir grupos de edad

edad_comuna <- clean_names(edad_comuna) |> 
  select(codigo_comuna, comuna, grupos_de_edad, poblacion_censada, hombres, mujeres, razon_hombre_mujer) |>
  filter(!grepl("País", comuna, ignore.case = TRUE) & !is.na(comuna)) |>
  filter(!grupos_de_edad %in% c("0 a 4", "5 a 9", "10 a 14", "15 a 19")) |>
  mutate(
    grupo_edad_unido = case_when(
      grupo_de_edad %in% c("20 a 24", "25 a 29", "30 a 34") ~ "20 a 34",
      grupos_de_edad %in% c("35 a 39", "40 a 44", "45 a 49") ~ "35 a 49",
      grupos_de_edad %in% c("50 a 54", "55 a 59", "60 a 64") ~ "50 a 64",
      grupos_de_edad %in% c("65 a 69", "70 a 74", "75 a 79") ~ "65 a 79",
      grupos_de_edad %in% c("80 a 84", "85 a 89", "90 a 94", "95 a 99", "100 y más") ~ "80 y más",
      TRUE ~ grupos_de_edad
    )
  ) |>
  group_by(codigo_comuna, comuna, grupo_edad_unido) |>
  summarise(
    poblacion_censada = sum(poblacion_censada),
    hombres = sum(hombres),
    mujeres = sum(mujeres),
    .groups = "drop"
  ) |>
  mutate(
    porcentaje_hombres = round((hombres / poblacion_censada) * 100, 2),
    porcentaje_mujeres = round((mujeres / poblacion_censada) * 100, 2)
  ) 

#Ahora hay que colocar cual es el mayor grupo  

  edad_comuna <- edad_comuna |>
  group_by(comuna) |>
   filter(!grepl("Total Comuna", grupo_edad_unido, ignore.case = TRUE)) |>
  filter(poblacion_censada == max(poblacion_censada)) |>
  ungroup()|>
  select(codigo_comuna, comuna, grupo_edad_unido, poblacion_censada, hombres, mujeres, porcentaje_hombres, porcentaje_mujeres)

```

# Código para limpiar base 3: Tendencia política de la comuna

```{r}

alcaldes <- read_excel("input/datos_alcalde.xlsx")

alcaldes <- clean_names(alcaldes)

alcaldes <- alcaldes |>
  filter(cargo == "ALCALDE")

alcaldes <- alcaldes |> 
  select(comuna,pacto, partido) |> 
  arrange(comuna)

write_csv(alcaldes, "data/tendencia.csv")
```

